### ISSUE TITLE
Blog refresh

### ISSUE THREAD

**Issue by joshmoore** [zarr-developers/zarr-developers.github.io#29]
In preparation for changing the URL here from https://zarr-developers.github.io/ to  https://zarr.dev, here are some rebranding suggestions for turning the "blog" into the primary landing page for Zarr:

## Outline/sitemap

- [ ] Landing page
  - [ ] Job opening
  - [x] Content from one pager
  - [ ] Super simple example
  - [ ] Drawings of what’s in a zarr https://twitter.com/notjustmoore/status/1465391574360207360/photo/1 
  - [ ] Projects using
  - [x] Embed video from Alistair
- [ ] Implementations
  - Related projects
  - N5
  - Exdir
- [ ] Projects using
  - [ ] Pangeo (--> Python?)
- [ ] Related libraries
  - [ ] Dask & xarray (--> Python?)
- [ ] About
  - Funding
  - Repositories
    - https://github.com/zarr-developers/community/issues?page=2&q=is%3Aissue+is%3Aopen
  - Steering council
- [ ] Slides
  - https://github.com/zarr-developers/community/issues/10 
- [ ] Artwork
  - https://github.com/zarr-developers/community/issues/11 
- [ ] Getting in touch
  - [x] https://github.com/zarr-developers/community/issues/1 
  - [x] Calendar
  - [ ] Stackoverflow(?)
  - [x] Gitter
  - [ ] Migrate notes from gdocs (hackmd?)
- [ ] Posts (Blog)
  - In the news: https://github.com/zarr-developers/community/issues/4 
  - Publications (retro-actively?)
  - New logo & url (thanks to NumFOCUS)
  - Job opening
  - tweets (reverse chronological)
    - https://twitter.com/opengeospatial/status/1466732898523004928
    - https://twitter.com/zarr_dev/status/1466789015357739010
    - https://twitter.com/notjustmoore/status/1432795729890877441
    - https://twitter.com/GerBI_GMB/status/1432747023715942407
    - https://twitter.com/carbonplanorg/status/1442559369539817478
    - https://twitter.com/ChelleGentemann/status/1427654394867183626
    - https://twitter.com/AbiIsNotABot/status/1334114956380229632
    - ...

## Other TODOs
- [x] favicon

cc: @zarr-developers/steering-council

**Comment by jakirkham** [comment]
Thanks for writing this up Josh! 😄

Do we want job opening in 2 places? Also what is going under funding or repositories (sorry not following the link)?

**Comment by joshmoore** [comment]
I'll start to either add content here or just go ahead and get a PR open, but funding is basically to list CZI EOSS and fiscal sponsorship by NumFOCUS and the repositories is to just explain what repos are out there.

**Comment by jakirkham** [comment]
Sorry not following the repo part still. Do you mean in the Zarr org or do you mean just implementations of Zarr? If the latter, it might be worth saying implementations instead of repos

**Comment by jakirkham** [comment]
Also +1 on a PR maybe it will make some of these fuzzy points clearer

**Comment by joshmoore** [comment]
> Sorry not following the repo part still.

See the current "About" page (https://zarr-developers.github.io/about/) it lists numcodecs, the spec, etc. in the org.

**Comment by joshmoore** [comment]
Now marking off issues that are completed on https://zarr.dev

**Comment by joshmoore** [comment]
Currently looking at github page themes if anyone has suggestions:

 - https://jekyllthemes.io/theme/bulma

**Comment by joshmoore** [comment]
Rough version of minimal-mistakes

<img width="1628" alt="Screen Shot 2021-12-17 at 20 42 22" src="https://user-images.githubusercontent.com/88113/146599211-a06f4c65-de3a-428f-b150-67ad09eb0b51.png">

**Comment by joshmoore** [comment]
Updated live site with the below (minimal-mistakes but happy to still swap)

![Screen Shot 2021-12-17 at 22 12 24](https://user-images.githubusercontent.com/88113/146608570-f0d4bdee-37b9-41e6-802c-0be9c34e6527.png)

![Screen Shot 2021-12-17 at 22 12 31](https://user-images.githubusercontent.com/88113/146608584-c5d1249a-6873-4cf1-ab9e-1f5b9563853c.png)

Only outstanding issue I'm aware of are the slides.

**Comment by jakirkham** [comment]
That looks really slick Josh! 😄

**Comment by joshmoore** [comment]
Thanks. I think everything is now handled to match https://zarr-developers.github.io/ feel free to add on top of it (directly on main)

**Comment by joshmoore** [comment]
New site is now live and former URLs from https://zarr-developers.github.io/ redirect. The TODO list above is still partially relevant has been captured in: https://github.com/zarr-developers/zarr-developers.github.io/issues/33
