### ISSUE TITLE
Improve discoverability of ZEP meetings info

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/zarr-developers.github.io#64]
Perhaps I'm doing things wrong, but had trouble refinding ZEP meeting info recently. We link to the community meetings from the main page, but not the ZEP meetings. This may make sense since community meetings are likely more interesting to most people. That said, maybe we can link just to meetings and have a list of meetings on a page with community meetings at the top. This would make it easier to find notes, invites, meeting links, etc.

**Comment by jakirkham** [comment]
cc @MSanKeys963 (in case you have thoughts here :)

**Comment by MSanKeys963** [comment]
Agree with you, @jakirkham. I meant to revamp the main website and include the info about ZEPs and ZEP meetings. Hopefully, I'll start with this in a few weeks.

In the meantime, I'll add info about ZEPs and meetings on the current homepage.

**Comment by jakirkham** [comment]
No worries. Just sharing this pain point since I ran into it recently 🙂

Thanks Sanket! 🙏
